# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Build Game
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build Game into dist folder
        runs-on: ubuntu-latest
        concurrency: build-game-group # optional: ensure only one action runs at a time
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            # - name: Install Dependencies
            #   run: npm install
            # - name: Delete old /dist folder
            #   run: npx del-cli dist --force
            # - name: Start Building folder
            #   run: node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --env mode=production --progress --config webpack.production.js
            #   working-directory: ${{ github.workspace }}
